Repository juntossomosmais/django-import-export-stomp, pull requests merged in 2023-10, with the labels that each got.

#2 [DEV] Feature/azure integration
  .gitignore
  .pre-commit-config.yaml
  Dockerfile
  azure-pipelines.yml
  example/project/celery.py
  example/project/settings.py
  import_export_stomp/admin.py
  import_export_stomp/admin_actions.py
  import_export_stomp/apps.py
  import_export_stomp/model_config.py
  import_export_stomp/models/exportjob.py
  import_export_stomp/models/importjob.py
  import_export_stomp/tasks.py
  poetry.lock
  pyproject.toml
  pytest.ini
  settings.py
  setup.cfg
  sonar-project.properties
  tests/integration/__init__.py
  tests/unit/__init__.py
  tests/unit/models/__init__.py
  tests/unit/models/test_exportjob.py
  tests/unit/models/test_importjob.py
  tests/unit/test_admin_actions.py
  tests/unit/test_apps.py
  tests/unit/test_fields.py
  tests/unit/test_model_config.py
  tests/unit/test_utils.py
Labels: development

#7 Release/azure integration
  .gitignore
  .pre-commit-config.yaml
  Dockerfile
  README.md
  azure-pipelines.yml
  example/README.md
  example/project/celery.py
  example/project/settings.py
  import_export_stomp/admin.py
  import_export_stomp/admin_actions.py
  import_export_stomp/apps.py
  import_export_stomp/model_config.py
  import_export_stomp/models/exportjob.py
  import_export_stomp/models/importjob.py
  import_export_stomp/tasks.py
  poetry.lock
  pyproject.toml
  pytest.ini
  settings.py
  setup.cfg
  sonar-project.properties
  tests/integration/__init__.py
  tests/unit/__init__.py
  tests/unit/models/__init__.py
  tests/unit/models/test_exportjob.py
  tests/unit/models/test_importjob.py
  tests/unit/test_admin_actions.py
  tests/unit/test_apps.py
  tests/unit/test_fields.py
  tests/unit/test_model_config.py
  tests/unit/test_utils.py
Labels: production

#4 refactor: excluded example from coverage and renamed everything to stomp
  .coveragerc
  .env
  .gitignore
  Dockerfile
  MANIFEST.in
  README.md
  docker-compose.yml
  example/README.md
  import_export_stomp/admin.py
  import_export_stomp/admin_actions.py
  import_export_stomp/fields.py
  import_export_stomp/locale/eu/LC_MESSAGES/django.po
  import_export_stomp/locale/pt/LC_MESSAGES/django.po
  import_export_stomp/management/__init__.py
  import_export_stomp/management/commands/__init__.py
  import_export_stomp/management/commands/pubsub.py
  import_export_stomp/migrations/0002_auto_20190923_1132.py
  import_export_stomp/migrations/0003_exportjob.py
  import_export_stomp/migrations/0004_exportjob_email_on_completion.py
  import_export_stomp/migrations/0005_exportjob_site_of_origin.py
  import_export_stomp/migrations/0006_auto_20191125_1236.py
  import_export_stomp/migrations/0007_auto_20210210_1831.py
  import_export_stomp/migrations/0008_alter_exportjob_id_alter_importjob_id.py
  import_export_stomp/migrations/0009_alter_exportjob_options_alter_importjob_options_and_more.py
  import_export_stomp/model_config.py
  import_export_stomp/models/exportjob.py
  import_export_stomp/models/importjob.py
  import_export_stomp/pubsub.py
  import_export_stomp/tasks.py
  import_export_stomp/utils.py
  poetry.lock
  pyproject.toml
  scripts/start-tests.sh
  settings.py
  tests/__init__.py
  tests/integration/test_pubsub/__init__.py
  tests/integration/test_pubsub/test_export.py
  tests/integration/test_pubsub/test_import.py
  tests/resources/__init__.py
  tests/resources/custom-rabbitmq-conf/enabled_plugins
  tests/resources/custom-rabbitmq-conf/rabbitmq.conf
  tests/resources/fake_app/__init__.py
  tests/resources/fake_app/apps.py
  tests/resources/fake_app/models.py
  tests/resources/fake_app/resources.py
  tests/unit/models/test_importjob.py
  tests/unit/test_admin_actions.py
  tests/unit/test_command.py
  tests/unit/test_fields.py
  tests/unit/test_pubsub.py
  tests/unit/test_utils.py
  tests/utils.py
Labels: development

#6 feat(example): added example and remove more unused things
  .env
  .gitignore
  Makefile
  README.md
  docker-compose.yml
  example/README.md
  example/poetry.lock
  example/project/__init__.py
  example/project/settings.py
  example/pyproject.toml
  example/winners/admin.py
  example/winners/urls.py
  import_export_stomp/admin_actions.py
  import_export_stomp/locale/eu/LC_MESSAGES/django.po
  import_export_stomp/locale/pt/LC_MESSAGES/django.po
  import_export_stomp/management/commands/import_export_pubsub.py
  import_export_stomp/migrations/0001_initial.py
  import_export_stomp/migrations/0003_exportjob.py
  import_export_stomp/migrations/0010_remove_exportjob_email_on_completion_and_more.py
  import_export_stomp/models/exportjob.py
  import_export_stomp/models/importjob.py
  scripts/start-example.sh
  tests/unit/test_command.py
Labels: development

#10 feat: updated readme with the correct variables, badges, and documentation
  README.md
  pyproject.toml
Labels: documentation

#11 feat: changed versions to reflect real usage and updated versions
  README.md
  poetry.lock
  pyproject.toml
Labels: documentation

#14 fix: fixed bigautofield and presigned add and change forms
  README.md
  docker-compose.yml
  example/project/settings.py
  example/winners/apps.py
  import_export_stomp/admin.py
  import_export_stomp/apps.py
  import_export_stomp/migrations/0011_alter_exportjob_id_alter_importjob_id.py
  import_export_stomp/resources.py
  import_export_stomp/tasks.py
  import_export_stomp/templates/widgets/signed_url_file.html
  import_export_stomp/utils.py
  pyproject.toml
  scripts/start-example.sh
  settings.py
  tests/integration/test_views.py
  tests/resources/fake_app/models.py
  tests/unit/test_resources.py
  tests/unit/test_utils.py
Labels: bug
